# Generated by Django 3.2.7 on 2021-09-28 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('state', models.CharField(choices=[('OK', 'Approved'), ('NO', 'Rejected')], max_length=2, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.requester')),
            ],
        ),
    ]
